import json
from pathlib import Path
import shutil
import tempfile
import unittest
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / 'scripts'))
from build_blog import build, load_articles, url

ROOT = Path(__file__).resolve().parents[1]


def example(slug='example-article', language='en', status='published'):
    return {
        'schema_version': 1, 'status': status, 'language': language, 'slug': slug,
        'title': 'Life on the Water', 'seo_title': 'Life on the Water | Cavelle',
        'meta_description': 'A test article about life on the water.', 'excerpt': 'A short test excerpt.',
        'category': 'Floating Living', 'author': {'name': 'Verified Author', 'url': '/about/'},
        'date_published': '2026-09-20', 'date_modified': '2026-09-21',
        'featured_image': {'url': 'https://media.example.org/articles/test.webp', 'alt': 'Waterfront view', 'width': 1200, 'height': 630},
        'blocks': [
            {'type': 'paragraph', 'text': 'Explore <script>alert(1)</script> responsibly.'},
            {'type': 'heading', 'level': 2, 'text': 'A closer look'},
            {'type': 'link', 'text': 'Explore available assets', 'href': '/floating-assets/'},
        ],
    }


class BlogBuildTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        base = Path(self.tmp.name)
        self.source = base / 'articles'
        self.public = base / 'public'
        self.source.mkdir()
        for language in ('en', 'ar'):
            dest = self.public / ('ar/' if language == 'ar' else '') / 'about/index.html'
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy(ROOT / 'public' / ('ar/' if language == 'ar' else '') / 'about/index.html', dest)

    def add_article(self, name, article):
        (self.source / (name + '.json')).write_text(json.dumps(article, ensure_ascii=False), encoding='utf-8')

    def test_static_index_and_article_with_seo_and_escape(self):
        self.add_article('example', example())
        self.add_article('arabic', example(language='ar'))
        build(self.source, self.public)
        path = self.public / 'blog/example-article/index.html'
        html = path.read_text()
        index = (self.public / 'blog/index.html').read_text()
        self.assertIn('<h1 class="h1">Life on the Water</h1>', html)
        self.assertEqual(html.count('<h1'), 1)
        self.assertIn('https://www.cavelleyachts.com/blog/example-article/', html)
        self.assertIn('BlogPosting', html)
        self.assertIn('BreadcrumbList', html)
        self.assertIn('datePublished', html)
        self.assertIn('media.example.org/articles/test.webp', html)
        self.assertIn('Explore available assets', html)
        self.assertIn('&lt;script&gt;', html)
        self.assertNotIn('<script>alert(1)</script>', html)
        self.assertIn('hreflang="ar"', html)
        self.assertIn('/blog/example-article/', index)
        self.assertIn('/ar/blog/example-article/', (self.public / 'ar/blog/index.html').read_text())
        self.assertTrue(html.startswith('<!-- Generated by'))

    def test_draft_not_visible_and_stale_generated_article_removed(self):
        a = example()
        self.add_article('example', a)
        build(self.source, self.public)
        article = self.public / 'blog/example-article/index.html'
        self.assertTrue(article.exists())
        a['status'] = 'draft'
        self.add_article('example', a)
        build(self.source, self.public)
        self.assertFalse(article.exists())
        self.assertNotIn('example-article', (self.public / 'blog/index.html').read_text())

    def test_no_translation_no_broken_article_language_toggle(self):
        self.add_article('example', example())
        build(self.source, self.public)
        html = (self.public / 'blog/example-article/index.html').read_text()
        self.assertNotIn('/ar/blog/example-article/', html)
        self.assertIn('href="/ar/blog/" class="lang-toggle"', html)

    def test_rejects_invalid_urls_and_does_not_write_on_validation_failure(self):
        self.assertRaises(ValueError, url, 'javascript:alert(1)')
        self.assertRaises(ValueError, url, '//evil.example/path')
        bad = example()
        bad['blocks'][2]['href'] = 'javascript:alert(1)'
        self.add_article('bad', bad)
        with self.assertRaises(ValueError):
            build(self.source, self.public)
        self.assertFalse((self.public / 'blog/index.html').exists())


if __name__ == '__main__':
    unittest.main()
