#!/usr/bin/env python3
"""Cavelle - deterministic sitemap generator + validator.

Discovers indexable routes from the actual site structure (public/**/index.html),
excludes utility/redirect/noindex pages, and writes a validated sitemap.xml.

Designed to run in CI *before* `wrangler pages deploy`: it exits non-zero on any
validation failure, so a broken sitemap can never reach production.

Route discovery rules (no manual URL list):
  - Only index.html files are routes (directory -> URL with trailing slash).
  - Any route containing a '404' or 'thank-you' path segment is excluded
    (utility / conversion pages - never indexable).
  - Any page whose <meta name="robots"> contains noindex is excluded.
  - Any route matching a redirect source in public/_redirects is excluded.

lastmod:
  - Taken from the last git commit that modified the page's index.html
    (real content metadata, never the deployment timestamp).
  - If git history is unavailable (e.g. shallow clone), lastmod is omitted
    entirely rather than invented.
"""

import argparse
import re
import subprocess
import sys
import xml.etree.ElementTree as ET
from datetime import datetime
from pathlib import Path

SMAP_NS = "http://www.sitemaps.org/schemas/sitemap/0.9"

# Utility/conversion path segments - such routes are never indexable.
# Rules by SEGMENT NAME (not URL list), so future /ar/xxx/thank-you/ etc. are caught too.
EXCLUDED_SEGMENTS = {"404", "thank-you"}


def discover_routes(root: Path):
    """Map every public/**/index.html to its site route ('/'-terminated)."""
    routes = {}
    for path in sorted(root.rglob("index.html")):
        rel = path.parent.relative_to(root)
        route = "/" if rel == Path(".") else "/" + rel.as_posix() + "/"
        routes[route] = path
    return routes


def route_is_excluded_segment(route: str) -> bool:
    segs = [s for s in route.split("/") if s]
    return any(seg.lower() in EXCLUDED_SEGMENTS for seg in segs)


def page_is_noindex(html_path: Path) -> bool:
    """True if the page's robots meta tag contains noindex."""
    try:
        text = html_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return True  # unreadable page - exclude to be safe
    m = re.search(
        r"<meta\s+name=[\"']robots[\"']\s+content=[\"']([^\"']*)[\"']",
        text,
        re.IGNORECASE,
    )
    return bool(m and "noindex" in m.group(1).lower())


def parse_redirect_sources(root: Path):
    """Redirect source prefixes from the Cloudflare Pages _redirects file."""
    sources = []
    f = root / "_redirects"
    if not f.is_file():
        return sources
    for line in f.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) >= 2:
            sources.append(parts[0])
    return sources


def matches_redirect(route: str, sources) -> bool:
    for src in sources:
        src_clean = src.rstrip("*").rstrip("/")
        if not src_clean or src_clean == "/":
            continue
        if route == src_clean or route == src_clean + "/" or route.startswith(src_clean + "/"):
            return True
    return False


def git_lastmod(page_file: Path):
    """ISO-8601 date of the last commit that touched this exact page file."""
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cI", "--", page_file.resolve().as_posix()],
            capture_output=True,
            text=True,
            timeout=30,
        )
        date = out.stdout.strip()
        if out.returncode == 0 and date:
            return date
    except Exception:
        pass
    return None


def build_urls(root: Path, base_url: str, use_lastmod: bool):
    routes = discover_routes(root)
    redirect_sources = parse_redirect_sources(root)

    entries = []
    excluded = []
    for route, path in routes.items():
        if route_is_excluded_segment(route):
            excluded.append((route, "utility page (404/thank-you)"))
        elif page_is_noindex(path):
            excluded.append((route, "meta robots noindex"))
        elif matches_redirect(route, redirect_sources):
            excluded.append((route, "redirect source in _redirects"))
        else:
            entries.append((route, path))

    # Deterministic ordering: EN routes first, then AR, alphabetical within each group.
    entries.sort(key=lambda rp: (rp[0].startswith("/ar") and rp[0] != "/", rp[0]))

    urls = []
    for route, path in entries:
        loc = base_url.rstrip("/") + route
        lastmod = git_lastmod(path) if use_lastmod else None
        urls.append((loc, lastmod))
    return urls, excluded


def render_xml(urls):
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- Auto-generated by scripts/generate_sitemap.py - do not edit manually. -->",
        f'<urlset xmlns="{SMAP_NS}">',
    ]
    for loc, lastmod in urls:
        esc = loc.replace("&", "&amp;").replace("<", "&lt;").replace('"', "&quot;")
        if lastmod:
            lines.append(f"<url><loc>{esc}</loc><lastmod>{lastmod}</lastmod></url>")
        else:
            lines.append(f"<url><loc>{esc}</loc></url>")
    lines.append("</urlset>")
    return "\n".join(lines) + "\n"


def validate(xml_text: str, expected_base: str):
    """Validate the generated sitemap. Returns list of error strings (empty = valid)."""
    errors = []

    # 1. XML well-formedness + structure
    try:
        root = ET.fromstring(xml_text)
    except ET.ParseError as e:
        return [f"XML parse error: {e}"]
    if root.tag != f"{{{SMAP_NS}}}urlset":
        errors.append(f"root element is {root.tag!r}, expected urlset in sitemap namespace")

    locs = []
    lastmods = []
    for url_el in root:
        if url_el.tag != f"{{{SMAP_NS}}}url":
            errors.append(f"unexpected element inside urlset: {url_el.tag}")
            continue
        loc_el = url_el.find(f"{{{SMAP_NS}}}loc")
        if loc_el is None or not (loc_el.text or "").strip():
            errors.append("a <url> entry is missing its <loc>")
            continue
        locs.append(loc_el.text.strip())
        lm_el = url_el.find(f"{{{SMAP_NS}}}lastmod")
        if lm_el is not None:
            lastmods.append(lm_el.text.strip())

    if not locs:
        errors.append("sitemap contains no URLs")

    # 2. Duplicate URLs
    dups = {l for l in locs if locs.count(l) > 1}
    for d in sorted(dups):
        errors.append(f"duplicate URL: {d}")

    # 3. URL format: absolute https://www canonical form only
    prefix = expected_base.rstrip("/") + "/"
    for loc in locs:
        if not loc.startswith(prefix):
            errors.append(f"URL not in canonical {prefix} form: {loc}")
        elif "http://" in loc or "//cavelleyachts.com" in loc.replace("https://www.cavelleyachts.com", ""):
            errors.append(f"malformed URL: {loc}")

    # 4. Excluded paths must be absent
    for loc in locs:
        segs = {s.lower() for s in loc[len(prefix) - 1:].split("/") if s}
        bad = segs & EXCLUDED_SEGMENTS
        if bad:
            errors.append(f"excluded path present in sitemap: {loc}")

    # 5. Deterministic ordering (EN routes first, then AR, alphabetical)
    def rank(loc):
        path = loc[len(prefix) - 1:]
        return (path.startswith("/ar") and path != "/", path)
    if locs != sorted(locs, key=rank):
        errors.append("URL ordering is not deterministic (EN then AR, alphabetical)")

    # 6. lastmod values must be valid ISO-8601 dates
    for lm in lastmods:
        try:
            datetime.fromisoformat(lm)
        except ValueError:
            errors.append(f"invalid lastmod value: {lm}")

    return errors


def main():
    ap = argparse.ArgumentParser(description="Generate and validate sitemap.xml")
    ap.add_argument("--root", default="public", help="site root directory (default: public)")
    ap.add_argument("--base", default="https://www.cavelleyachts.com", help="canonical site origin")
    ap.add_argument("--output", default="public/sitemap.xml", help="output file path")
    ap.add_argument("--no-lastmod", action="store_true", help="omit lastmod even if git history exists")
    args = ap.parse_args()

    root = Path(args.root)
    if not root.is_dir():
        print(f"ERROR: site root '{args.root}' not found", file=sys.stderr)
        return 2

    use_lastmod = not args.no_lastmod
    urls, excluded = build_urls(root, args.base, use_lastmod)

    # If git metadata is unavailable, omit lastmod everywhere (consistency over invention).
    if use_lastmod and urls and all(lm is None for _, lm in urls):
        print("NOTE: git history unavailable - omitting lastmod entirely.")
        urls = [(loc, None) for loc, _ in urls]
    if use_lastmod and any(lm is None for _, lm in urls):
        missing = sum(1 for _, lm in urls if lm is None)
        print(f"NOTE: {missing} URL(s) lack git lastmod - lastmod omitted for those URLs.")

    xml_text = render_xml(urls)

    errors = validate(xml_text, args.base)

    if errors:
        print("SITEMAP VALIDATION FAILED:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return 1

    Path(args.output).write_text(xml_text, encoding="utf-8")

    en = sum(1 for loc, _ in urls if "/ar/" not in loc)
    ar = len(urls) - en
    lm_count = sum(1 for _, lm in urls if lm)
    print(f"Sitemap OK: {len(urls)} URLs ({en} EN, {ar} AR), {lm_count} with lastmod.")
    for route, reason in excluded:
        print(f"  excluded: {route}  [{reason}]")
    print(f"Written to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
